CREATE TABLE [dbo].[staging_ng_appointment_data_]
(
[Appt_new_key] [uniqueidentifier] NULL,
[Practice_id] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[created_by] [int] NULL,
[create_timestamp] [datetime] NULL,
[modified_by] [int] NULL,
[modify_timestamp] [datetime] NULL,
[appt_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[begintime] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[res_id] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[appt_loc_id] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[enc_uid] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[enc_nbr] [bigint] NULL,
[appt_nbr] [bigint] NULL,
[appt_duration] [int] NULL,
[interval] [int] NULL,
[enc_loc_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[enc_loc_id] [uniqueidentifier] NULL,
[enc_rendering_name] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[enc_rendering_id] [uniqueidentifier] NULL,
[appt_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[appt_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[start_ind] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[slot_info] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[enc_slot_nbr] [int] NULL,
[slot_time] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[appt_kept_ind] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cancel_ind] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[resched_ind] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[delete_ind] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[enc_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[checkin_datetime] [datetime] NULL,
[enc_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cycle_Min_slottime_to_Kept] [int] NULL,
[primarycare_prov_id] [uniqueidentifier] NULL,
[appt_id] [uniqueidentifier] NULL,
[event_id] [uniqueidentifier] NULL,
[app_person_id] [uniqueidentifier] NULL,
[enc_person_id] [uniqueidentifier] NULL,
[person_id] [uniqueidentifier] NULL,
[cancel_reason] [uniqueidentifier] NULL,
[resched_reason] [uniqueidentifier] NULL,
[appt_made_when] [datetime] NULL,
[appt_made_by] [int] NULL,
[workflow_status] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[workflow_room] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apt_By_PCP] [varchar] (52) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Apt_notlinked_toPerson] [int] NOT NULL,
[Nbr_PCP_Appt] [int] NOT NULL,
[Nbr_NonPCP_Appt] [int] NOT NULL,
[nbr_kept_and_linked_enc] [int] NOT NULL,
[nbr_future] [int] NOT NULL,
[nbr_kept_not_linked_enc] [int] NOT NULL,
[nbr_no_show] [int] NOT NULL,
[nbr_cancelled] [int] NOT NULL,
[nbr_deleted] [int] NOT NULL,
[nbr_rescheduled] [int] NOT NULL,
[slot_dur_appt_records] [int] NULL,
[slot_dur_kept_and_linked_enc] [int] NULL,
[slot_dur_future] [int] NULL,
[slot_dur_kept_not_linked_enc] [int] NULL,
[slot_dur_no_show] [int] NULL,
[slot_dur_cancelled] [int] NULL,
[slot_dur_deleted] [int] NULL,
[slot_dur_rescheduled] [int] NULL,
[nbr_bill_w_appt] [int] NOT NULL,
[nbr_non_bill_w_appt] [int] NOT NULL,
[enc_billable_linked_appt_dur_mins] [int] NULL,
[enc_non_billable_linked_appt_dur_mins] [int] NULL,
[User_Checkout_MA] [int] NULL,
[Cycle_Min_Kept_CheckedOut] [int] NULL,
[User_ReadyforProvider_MA] [int] NULL,
[Cycle_Min_Kept_ReadyForProvider] [int] NULL,
[Cycle_Min_Kept_Charted] [int] NULL,
[Cycle_Min_ReadyforProvider_Checkout] [int] NULL,
[user_created_Encounter] [int] NULL
) ON [PRIMARY]
GO
