CREATE TABLE [dbo].[staging_ng_data_transaction_]
(
[enc_id] [uniqueidentifier] NOT NULL,
[location_id] [uniqueidentifier] NULL,
[person_id] [uniqueidentifier] NOT NULL,
[charge_id] [uniqueidentifier] NOT NULL,
[trans_id] [uniqueidentifier] NOT NULL,
[provider_id] [uniqueidentifier] NULL,
[payer_id] [uniqueidentifier] NULL,
[created_by] [int] NOT NULL,
[tran_code_id] [uniqueidentifier] NOT NULL,
[reason_code_id] [uniqueidentifier] NULL,
[enc_bill_date] [date] NULL,
[chg_closing_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[txn_batch_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[batch_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[txn_post_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[post_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[txn_closing_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[closing_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[adj_amt_enc_mon] [numeric] (19, 2) NULL,
[adjust_pd] [numeric] (19, 2) NULL,
[pymt_adj] [numeric] (19, 2) NULL,
[pymts_amt_enc_mon] [numeric] (19, 2) NULL,
[adj_amt_later_mon] [numeric] (19, 2) NULL,
[adjust_pd_later] [numeric] (19, 2) NULL,
[pymt_adj_later] [numeric] (19, 2) NULL,
[pymts_amt_later_mon] [numeric] (19, 2) NULL,
[refunds_amt] [numeric] (19, 2) NULL,
[paid_amt] [numeric] (19, 2) NULL,
[adj_amt] [numeric] (19, 2) NULL
) ON [PRIMARY]
GO
