CREATE TABLE [dbo].[staging_ng_data_charge_]
(
[enc_id] [uniqueidentifier] NOT NULL,
[charge_id] [uniqueidentifier] NOT NULL,
[provider_id] [uniqueidentifier] NULL,
[person_id] [uniqueidentifier] NOT NULL,
[location_id] [uniqueidentifier] NULL,
[service_item_id] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cpt4_code_id] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[icd9cm_code_id] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[icd9cm_code_id_2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[icd9cm_code_id_3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[icd9cm_code_id_4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[created_by] [int] NOT NULL,
[enc_bill_date] [date] NULL,
[chg_closing_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[chg_mod_date] [datetime] NOT NULL,
[zero_bal_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[credit_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Txn_closing_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Txn_batch_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Txn_override_closing_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Txn_post_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[days_chg_close_to_txn_close] [int] NULL,
[days_chg_close_to_txn_post] [int] NULL,
[days_chg_close_to_txn_batch] [int] NULL,
[days_txn_batch_to_txn_post] [int] NULL,
[days_enc_to_chg_close] [int] NULL,
[chg_amt_enc_mon] [numeric] (19, 2) NOT NULL,
[chg_amt_later_mon] [numeric] (19, 2) NOT NULL,
[amt] [numeric] (19, 2) NOT NULL,
[cob1_amt] [numeric] (19, 2) NOT NULL,
[cob2_amt] [numeric] (19, 2) NOT NULL,
[cob3_amt] [numeric] (19, 2) NOT NULL,
[pat_amt] [numeric] (19, 2) NOT NULL
) ON [PRIMARY]
GO
